networks:
  mynetwork:
    driver: bridge

services:
  sfs:
    restart: unless-stopped
    build:
      context: services/website/.
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    hostname: website
  pocketbase:
    restart: unless-stopped
    build:
      context: services/pocketbase/.
    ports:
      - "8090:8090"
    networks:
      - mynetwork
    hostname: database
